{"name": "Ручка /api/v1/orders/accept/", "status": "passed", "description": "Создаём курьера, логинимся, принимаем заказ с несуществующим id", "start": 1710444108793, "stop": 1710444108864, "uuid": "d3dd46e2-b725-4b5f-ac43-6dd1edc9e996", "historyId": "36cdde27c4f93e161758ac1bc29300c7", "testCaseId": "36cdde27c4f93e161758ac1bc29300c7", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_wrong_track_number_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "23240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}