{"name": "Ручка /api/v1/orders/track", "status": "passed", "description": "Получаем заказ по неправильному номеру", "steps": [{"name": "Запрос на получение заказа по неправильному номеру", "status": "passed", "start": 1710620430596, "stop": 1710620430666}, {"name": "Проверки на статус и ответ", "status": "passed", "start": 1710620430666, "stop": 1710620430666}], "start": 1710620430596, "stop": 1710620430666, "uuid": "deaf213e-ebbc-44a1-a643-ea42841885b9", "historyId": "4435357238e942382346d827b7e6ab17", "testCaseId": "4435357238e942382346d827b7e6ab17", "fullName": "test_api.tests.test_take_order_number.TestTakeOrderNumber#test_take_order_number_wrong_number_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_take_order_number"}, {"name": "subSuite", "value": "TestTakeOrderNumber"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "23412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_take_order_number"}]}