{"name": "Ручка /api/v1/orders/accept/", "status": "passed", "description": "Создаём заказ, получаем трек номер, принимаем заказ с некорректным id курьера", "start": 1710612153802, "stop": 1710612153889, "uuid": "17aa7e5e-cac8-47d7-b5a0-541c0dc24965", "historyId": "a880846fcbfb59b7d59484d90ca1336b", "testCaseId": "a880846fcbfb59b7d59484d90ca1336b", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_wrong_courier_id_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "22020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}