{"name": "Ручка /api/v1/courier/login", "status": "passed", "description": "Пробуем залогиниться, используя некорректные данные, ожидаем получить ошибку 400 и текст 'Недостаточно данных для входа'", "steps": [{"name": "Запрос на авторизацию с комбинацией заполненности логина и пароля", "status": "passed", "start": 1710620430249, "stop": 1710620430298}, {"name": "Проверки на статус и ответ", "status": "passed", "start": 1710620430298, "stop": 1710620430298}], "parameters": [{"name": "login", "value": "None"}, {"name": "password", "value": "'None'"}], "start": 1710620430249, "stop": 1710620430306, "uuid": "e9bc9e45-356a-465e-ad21-ad10c350afd1", "historyId": "ff482f7902d5ff98a4ffe78c815c7276", "testCaseId": "14eb7ed67efb59bc0210cf649d3f4709", "fullName": "test_api.tests.test_login_courier.TestLoginCourier#test_login_courier_empty_fields_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "23412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_login_courier"}]}