{"name": "test_accept_order_twice_error", "status": "passed", "description": "Создаём заказ, получаем трек номер, создаём двух курьеров, логинимся, получаем id, затем принимаем один заказ каждым курьером.", "start": 1710094437678, "stop": 1710094438204, "uuid": "91e96157-f3e8-4740-b0bf-b531b3263e90", "historyId": "60f7f35133c746add7310232865867bd", "testCaseId": "60f7f35133c746add7310232865867bd", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_twice_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "38908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}