{"name": "Ручка /api/v1/orders/accept/", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_api.tests.test_accept_order.TestAcceptOrder object at 0x000001566927D480>, login_new_courier = 277691, create_order = 395220\n\n    @allure.title(\"Ручка /api/v1/orders/accept/\")\n    @allure.description(\"Создаём заказ, получаем трек номер, создаём курьера, логинимся, получаем id, затем принимаем заказ\")\n    def test_accept_order_positive(self, login_new_courier, create_order):\n        track_number = create_order\n        id_courier = login_new_courier\n        response = requests.put(URLS.URL_MAIN + URLS.URL_ACCEPT_ORDER + str(track_number) + \"?\" + \"courierId=\" + str(id_courier))\n    \n>       assert response.status_code == 200\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\ntest_api\\tests\\test_accept_order.py:16: AssertionError"}, "description": "Создаём заказ, получаем трек номер, создаём курьера, логинимся, получаем id, затем принимаем заказ", "start": 1710617467793, "stop": 1710617467883, "uuid": "658c86f2-f619-4e2c-825e-61e988c3e3dc", "historyId": "6c14eb751e7860991926d85c20479465", "testCaseId": "6c14eb751e7860991926d85c20479465", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_positive", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "5592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}