{"name": "test_accept_order_without_courier_id_or_track_number_error[-]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_api.tests.test_accept_order.TestAcceptOrder object at 0x000001F4B22F34C0>, track_number = '', id_courier = ''\n\n    @allure.description(\n        \"Принимаем заказ с комбинациями заполненности полей: трек номер и курьер\")\n    @pytest.mark.parametrize(\n        \"track_number, id_courier\",\n        [\n            AcceptOrder.Accept_0,\n            AcceptOrder.Accept_1,\n            AcceptOrder.Accept_2\n        ]\n    )\n    def test_accept_order_without_courier_id_or_track_number_error(self, track_number, id_courier):\n        response = requests.put(URLS.URL_MAIN + URLS.URL_ACCEPT_ORDER + str(track_number) + \"?\" + \"courierId=\" + str(id_courier))\n    \n>       assert response.status_code == 400\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntest_api\\tests\\test_accept_order.py:51: AssertionError"}, "description": "Принимаем заказ с комбинациями заполненности полей: трек номер и курьер", "parameters": [{"name": "track_number", "value": "''"}, {"name": "id_courier", "value": "''"}], "start": 1710094437593, "stop": 1710094437672, "uuid": "89a671ca-9ec0-4a1a-a1ee-0d91fc97227d", "historyId": "6276f43c1f2f011d0dd42e5d7baf5b83", "testCaseId": "6276f43c1f2f011d0dd42e5d7baf5b83", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_without_courier_id_or_track_number_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "38908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}